language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '8'
script:
  - npm run compile
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
